/*********************************************************************
 *
 * Project:      LIN 2.1 driver suite
 *
 * File name:    lin_cfg_types.h
 *
 * Description:  configuration file for LIN 2.1 driver
 *
 * Copyright:    (c) ST Microelectronics 2009
 *
 * Target:       all
 *
 * This file was automatically generated by
 * lingen 3.5.0.STM built at 14:44:55 on May  7 2010
 * (c) 2009 by STMicroelectronics, Catania
 *
 * Not to be changed by the user!
 *
 *
 *********************************************************************/

/** \file lin_cfg_types.h
 */

#ifndef LIN_CFG_TYPES_H
#define LIN_CFG_TYPES_H


#define LIN_CFG_TYPES_H_MAJOR_VERSION          3
#define LIN_CFG_TYPES_H_MINOR_VERSION          5
#define LIN_CFG_TYPES_H_PATCH_VERSION          0

#define LIN_CFG_TYPES_H_STM

#ifdef LIN_VERSION_CONTROL_H
  #error "lin_version_control.h shall not be included in h-files and shall be the last file to be included in a c-file!"
#endif /* LIN_VERSION_CONTROL_H */
/*
 * definition of the interfaces used
 */
#define SCI1_USED

/*
 * important defines for array size definitions
 */
#define LIN_FLAG_DATA_LEN               ((LIN_FLAG_NR_MAX+CHAR_BIT-1) / CHAR_BIT)
#define LIN_FRAME_BUF_SIZE              26
#define LIN_TRANSMIT_FLAG_DATA_SIZE     6
#define LIN_CHANGED_FLAG_DATA_SIZE      4
#define LIN_FRAME_COUNT                 4
#define LIN_DIAGNOSTIC_ONLY             LIN_TAB_Diagnostic
#define LIN_MASTER_ONLY                 LIN_TAB_MasterOnly
#define LIN_SLAVE_ONLY                  LIN_TAB_SlaveOnly

/*
 * important defines that configure the code depending
 * on information extracted from the LDF file
 */ 
#define LIN_SLAVE_NODE 1

#define LIN_21


/*
 * enumeration of frame identifiers
 */
typedef enum
{
  LIN_FRAME_CCU_2 =    0, 
  LIN_FRAME_CLM_1 =    1, 
  LIN_FRAME_SlaveResp =    2, 
  LIN_FRAME_MasterReq =    3, 
  LIN_FRAME_NR_MAX =    4,
  LIN_INVALID_FRAME_INDEX = 0x7FFF
} l_frame_handle;


#endif

